const prompt = require("prompt-sync") ({ sigint: true})
console.log("====================")
console.log("KALKULATOR LINGKARAN")
console.log("====================")
let r = Number(prompt("Jari-jari : "))
let d = Number(prompt("Diameter : "))